config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create]    
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comment_counter

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_post_likes_count

  def update_post_likes_count
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id

  validates :title, presence: true, length: { minimum: 3, maximum: 250 }

  after_save :update_post_counter

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_recent_posts
    posts.order('created_at DESC').first(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # method to return the current user
  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]

    if @comment.save
      flash[:success] = 'Comment created!'
      redirect_to user_post_path(current_user, @comment.post)
    else
      render :create
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new
    @like.post_id = params[:post_id]

    if @like.save
      flash[:success] = 'Liked!'
      redirect_to user_post_path(current_user, @like.post)
    else
      render :create
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts or /posts.json
  def index
    @user = User.find(params[:user_id])
  end

  # GET /posts/1 or /posts/1.json
  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @author = current_user
    @post = Post.new(post_params)
    @post.author = @author
    if @post.save
      flash[:notice] = 'Post saved successfully.'
      redirect_to user_path(@author)
    else
      flash.now[:error] = 'Error: Post could not be saved.'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_add_comment.html.erb
<%= form_with model: Comment, url: user_post_comments_path(@post.author, @post) do |form| %>
    <div>
        <%= form.label 'Add Comment' %> <br/><br/>
        <%= form.text_area :text, placeholder: 'Add Comment', row: 20, required: true %> <br/>
    </div>
    <div>
        <%= form.submit 'Add Comment' %>
    </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_add_like.html.erb
<section>
    <%= form_with model: Like, url: user_post_likes_path(@post.author, @post) do |form| %>
    <%= form.submit 'Like' %>
    <% end %>
</section>

app/views/posts/index.html.erb
<section>
<div class = 'the-user'>
    <div class = 'user-activity'>
        <h2><%= @user.name %></h2>
        <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
</div>
<div class='user-posts'>
    <% @user.posts.each do |post| %>
    <div class='listed-posts'>
    <h4><%= link_to post.title, user_post_path(@user, post) %></h4>
    <p><%= post.text %></p>

    <span class = 'comment-likes'>
        Comments: <%= post.comments_counter || 0 %>
        Likes: <%= post.likes_counter || 0 %>
    </span>
    </div>
    <ul class = 'comments-info'>
       <% if post.five_recent_comments.length == 0 %>
         <p>No comments yet</p>
         <% else %>
            <% post.five_recent_comments.each do |comment| %> 
                <li><%= comment.author %> : <%= comment.text %></li>
                <% end %>
        <% end %>
    </ul>
    <% end %>
</div>  
</section>

app/views/posts/new.html.erb
<section>

    <p>Create a new Post:</p>
    <%= form_with model: Post, url: user_posts_url, class: "form" do |f|  %>
   <%= f.text_field :title, placeholder:"Title", id:"post_title", autofocus: true %>
  
  <div>
   <%= f.text_area :text, placeholder:"Write your content...", id:"post_text"%>
  </div>
  <div id="buttons_div">
   <%= f.submit "Save your post" %>
  </div>
<% end %>
</section>

app/views/posts/show.html.erb
<section>
    <div class = 'listed-posts'>
        <h4><%= @post.title%> by <%= @post.author.name%></h4>
        <p><%= @post.text  %></p>
        <span class = 'comment-likes'>
            Comments: <%= @post.comments_counter || 0 %>
            <%= render 'comments/add_comment' %>
            Likes: <%= @post.likes_counter || 0 %>
            <%= render 'likes/add_like' %>            
    </div>
    <ul class = 'comments-info'>
        <% if @post.comments.length == 0 %>
            <p>No comments yet</p>
        <% else %>
            <% @post.comments.each do |comment| %>
                <li><%= comment.author.name %> : <%= comment.text %></li>
            <%end%>
        <%end%>
    </ul>
</section>

app/views/users/index.html.erb
<section>
    <ul class = 'user-style-home'>
        <% @users.each do |user| %>
            <li>
                <div class = 'users-photo'>
                    <img src='<%= user.photo %>' alt = '<%= user.name %> photo' />
                </div>
                <div class = 'user-detail'>
                    <h2><%= link_to user.name, user_path(user) %></h2>
                    <p>Number of posts: <%= user.posts_counter %></p>
                </div>
            </li>
        <%end%>
    </ul>
</section>

app/views/users/show.html.erb
<section>
<div class = 'user-info'>
    <div class = 'user-photo'>
        <img src='<%= @user.photo %>' alt = '<%= @user.name %> photo' />
    </div>
    <div class = 'user-detail'>
        <h2> <%= @user.name %></h2>
        <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
</div>
<div class = 'bio'>
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
</div>

<div class = 'posts'>
    <% @user.three_recent_posts.each do |post| %>
        <div class = 'myposts'>
            <h4><% link_to post.title, user_post_path(@user, post)  %></h4>
            <p><%= post.text %></p>
            <span class = 'comments-likes'>
                Comments: <%= post.comments_counter || 0 %>
                Likes: <%= post.likes_counter || 0 %>
            </span>
        </div>
    <% end %>
</div>
<button class = 'view-all-posts'>
    <%= link_to 'see all posts', user_posts_path(@user) %>
</button>
</section>